# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |n|
    n.vm.box = "hashicorp/bionic64"
    n.vm.hostname = "vm1"
    config.vm.network "private_network", ip: "192.168.56.4"
    n.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end 

  end


  config.vm.define "vm2" do |n|
    n.vm.box = "hashicorp/bionic64"
    n.vm.hostname = "vm1"
    config.vm.network "private_network", ip: "192.168.56.5"
     n.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end 

  end

  config.vm.define "vm3" do |n|
    n.vm.box = "hashicorp/bionic64"
    n.vm.hostname = "vm1"
    config.vm.network "private_network", ip: "192.168.56.6"
     n.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end 

  end

end
